hitchify/urls.py
from django.urls import path, include
from hitchifyPY import settings
from . import views
from django.contrib.auth import views as authviews
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', authviews.LoginView.as_view(), name='index'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),

    path('countries/', views.countries, name='countries'),
    path('country/<country_id>', views.country, name='country'),
    path('country/<country_id>/posts', views.country, name='country_post'),
    path('country/<country_id>/add_post/', views.add_post, name='add_post'),
    path('country/<country_id>/edit', views.edit_country, name='edit_country'),
    path('add_country/', views.add_country, name='add_country'),

    path('add_language/', views.add_language, name='add_language'),
    path('connect_lang_country/', views.connect_lang_country, name='connect_lang_country'),

    path('hitchspots/', views.hitchspots, name='hitchspots'),
    path('hitchspot/<hitchspot_id>', views.hitchspot, name='hitchspot'),
    path('hitchspot/<hitchspot_id>/add_comment/', views.add_comment_to_hitchspot,
       name='add_comment_to_hitchspot'),
    path('hitchspot/<hitchspot_id>/edit_comment/', views.edit_comment_hitchspot,
       name='edit_comment_hitchspot'),
    path('hitchspot/<hitchspot_id>/del_comment/', views.del_comment_hitchspot,
       name='del_comment_hitchspot'),
    path('country/<country_id>/hitchspot/<spot_id>/add_feedback/', views.add_feedback_to_spot, name='add_feedback_to_spot'),
    path('hitchspot/<spot_id>/add_photo/', views.add_photo_to_spot, name='add_photo_to_spot'),
    path('hitchspot/<spot_id>/del_photo/<photo_id>', views.del_photo_from_spot, name='del_photo_from_spot'),
    path('hitchspot/<spot_id>/like_spot_comment/', views.like_spot_comment, name='like_spot_comment'),

    path('forum/', views.forum, name='forum'),

    path('post/<post_id>', views.post, name='post'),
    path('post/<post_id>/like', views.like_post, name='like_post'),
    path('post/<post_id>/edit', views.edit_post, name='edit_post'),
    path('post/<post_id>/add_comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('post/<post_id>/edit_comment/', views.edit_comment_post, name='edit_comment_post'),
    path('post/<post_id>/del_comment/', views.del_comment_post, name='del_comment_post'),
    path('post/<post_id>/add_photo/', views.add_photo_to_post, name='add_photo_to_post'),
    path('post/<post_id>/del_photo/<photo_id>', views.del_photo_from_post, name='del_photo_from_post'),
    path('post/<post_id>/like_post_comment/', views.like_post_comment, name='like_post_comment'),

    path('guides/', views.guides, name='guides'),
    path('guide/<guide_id>', views.guide, name='guide'),
    path('guide/<guide_id>/edit', views.edit_guide, name='edit_guide'),
    path('add_guide/', views.add_guide, name='add_guide'),
    path('guide/<guide_id>/add_photo/', views.add_photo_to_guide, name='add_photo_to_guide'),
    path('guide/<guide_id>/del_photo/<photo_id>', views.del_photo_from_guide, name='del_photo_from_guide'),

    path('guide/<guide_id>/add_suggestion', views.add_suggestion, name='add_suggestion'),
    path('guide/<guide_id>/see_suggestions', views.see_suggestions, name='see_suggestions'),

    path('suggestions/<gf_id>/delete', views.delete_suggestion, name='del_suggestion'),

    path('administration/', views.administration, name='administration'),

    path('map/', views.hitchify_map, name='map'),
    path('map/<country_id>', views.hitchify_map_country, name='map_country'),
    path('map_xml/', views.hitchify_xml, name='map_xml'),
    path('map_xml/<country_id>', views.hitchify_xml_country, name='map_xml_country'),

    path('add_point/', views.add_point, name='add_point'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hitchifyPY/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hitchify/', include('hitchify.urls')),
    path('', include('hitchify.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hitchify/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db import connection
from django.db.models.signals import post_save
from django.dispatch import receiver


class MyUser(models.Model):
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    # base_user = models.IntegerField(default=-1)
    base_user = models.OneToOneField(User, on_delete=models.CASCADE)
    gender = models.CharField(max_length=20)
    birth_date = models.DateField()
    country = models.CharField(max_length=255)
    city = models.CharField(max_length=255)

    # @receiver(post_save, sender=User)
    # def create_user_profile(sender, instance, created, **kwargs):
    #     if created:
    #         MyUser.objects.create(user=instance)
    #
    # @receiver(post_save, sender=User)
    # def save_user_profile(sender, instance, **kwargs):
    #     instance.myuser.save()

    class Meta:
        managed = True
        db_table = 'myuser'


class Country(models.Model):
    country_name = models.CharField(max_length=255)
    short_description = models.CharField(max_length=1500)
    national_currency = models.CharField(max_length=255)
    hitchrating = models.FloatField(blank=True, null=True)

    @property
    def loyal_users(self):
        with connection.cursor() as cursor:
            cursor.execute('SELECT us.username '
                           'FROM auth_user us '
                           'WHERE NOT EXISTS (SELECT * '
                                             'FROM (SELECT fp.id AS post_id '
                                                   'FROM country cou '
                                                   'INNER JOIN forum_post fp ON fp.country_id=cou.id '
                                                   'WHERE cou.id = %s) cp '
                                                   'WHERE NOT EXISTS (SELECT * '
                                                                     'FROM comment c '
                                                                     'WHERE c.user_id = us.id AND c.post_id=cp.post_id))',
                           [self.id])
            loyalists = cursor.fetchall()
        return loyalists

    @property
    def expert_users(self):
        with connection.cursor() as cursor:
            cursor.execute('SELECT auth_user.username, country.country_name, COUNT(hitchspot.id) AS spots '
                           'FROM ((auth_user INNER JOIN hitchspot ON auth_user.id = hitchspot.user_id) '
                           'INNER JOIN country ON country.id = hitchspot.country_id) '
                           'INNER JOIN forum_post ON forum_post.user_id = auth_user.id '
                           'WHERE country.id = %s '
                           'GROUP BY auth_user.username, country.country_name '
                           'HAVING COUNT(hitchspot.id)>=2;', [self.id])
            experts = cursor.fetchall()
        return experts

    @property
    def most_active_user(self):
        with connection.cursor() as cursor:
            cursor.execute('SELECT auth_user.username, COUNT(forum_post.user_id) AS posted_last_week '
                           'FROM forum_post '
                           'INNER JOIN auth_user ON auth_user.id = forum_post.user_id '
                           'WHERE forum_post.country_id = %s '
                           'GROUP BY forum_post.user_id, auth_user.username '
                           'HAVING COUNT (forum_post.user_id)=( '
                           'SELECT MAX(mycount) '
                           'FROM (SELECT user_id, COUNT(forum_post.user_id) AS mycount '
                           'FROM forum_post '
                           'WHERE forum_post.country_id = %s AND creation_date > current_date - interval \'7 days\' '
                           'GROUP BY user_id) AS auxTable );', [self.id, self.id])
            most_active_user = cursor.fetchall()
        return most_active_user

    @property
    def languages(self):
        res_languages = Language.objects.raw('SELECT id, language_name '
                                             'FROM language '
                                             'WHERE id IN (SELECT language_id '
                                             'FROM language_to_country '
                                             'WHERE country_id = %s)', [self.id])
        res_languages_list = []
        for lang in res_languages:
            res_languages_list.append(lang.language_name)

        return res_languages_list

    @property
    def hitchspots(self):
        res_hitchspots = Hitchspot.objects.raw('SELECT * '
                                               'FROM hitchspot '
                                               'WHERE country_id = %s '
                                               'ORDER BY id ASC', [self.id])

        res_hitchspots_list = []
        for spot in res_hitchspots:
            res_hitchspots_list.append(spot)
        return res_hitchspots_list

    @property
    def forum_posts(self):
        res_forum_posts = ForumPost.objects.raw(
            'SELECT * '
            'FROM forum_post fp '
            'INNER JOIN auth_user au ON fp.user_id = au.id '
            'WHERE fp.country_id = %s '
            'ORDER BY fp.id ASC', [self.id])

        res_forum_posts = list(res_forum_posts)
        return res_forum_posts

    class Meta:
        managed = True
        db_table = 'country'


class ForumPost(models.Model):
    title = models.CharField(max_length=255)
    body_text = models.TextField()
    likes = models.IntegerField(default=0)
    creation_date = models.DateField(auto_now_add=True)
    last_update = models.DateField(blank=True, null=True)
    user = models.ForeignKey(User, models.DO_NOTHING)
    country = models.ForeignKey(Country, models.DO_NOTHING)

    @property
    def photos(self):
        with connection.cursor() as cursor:
            cursor.execute('SELECT * '
                           'FROM photo '
                           'WHERE post_id = %s', [self.id])
            photos = cursor.fetchall()
        return photos

    @property
    def comments(self):
        res_comments = Comment.objects.raw('SELECT * '
                                           'FROM comment '
                                           'WHERE parent_comment_id IS NULL AND post_id = %s '
                                           'ORDER BY id ASC', [self.id])
        res_comments_list = []
        for comment in res_comments:
            res_comments_list.append(comment)

        return res_comments_list

        # with connection.cursor() as cursor:
        #     cursor.execute('SELECT * '
        #                    'FROM comment '
        #                    'WHERE post_id = %s ', [self.id])
        #     comments = cursor.fetchall()
        #     print(comments)
        #     return comments

    class Meta:
        managed = True
        db_table = 'forum_post'


class Guide(models.Model):
    title = models.CharField(max_length=255)
    body_text = models.TextField()
    short_summary = models.TextField(blank=True, null=True)
    creation_date = models.DateField(auto_now_add=True)
    update_date = models.DateField(blank=True, null=True)
    user = models.ForeignKey(User, models.DO_NOTHING)

    @property
    def photos(self):
        with connection.cursor() as cursor:
            cursor.execute('SELECT * '
                           'FROM photo '
                           'WHERE guide_id = %s', [self.id])
            photos = cursor.fetchall()
        return photos

    @property
    def top_contributors(self):
        with connection.cursor() as cursor:
            cursor.execute('SELECT auth_user.username '
                           'FROM guide_feedback INNER JOIN auth_user on auth_user.id = guide_feedback.user_id '
                           'GROUP BY guide_feedback.user_id, auth_user.username '
                           'HAVING COUNT(guide_feedback.user_id) = (SELECT MAX(mycount)'
                           'FROM (SELECT guide_feedback.user_id, COUNT(guide_feedback.user_id) AS mycount '
                           'FROM guide_feedback '
                           'WHERE guide_id = %s '
                           'GROUP BY guide_feedback.user_id) AS bruh1)',
                           [self.id])
            top_contributor = cursor.fetchall()
            print(top_contributor)
            return top_contributor

    class Meta:
        managed = True
        db_table = 'guide'


class GuideFeedback(models.Model):
    title = models.CharField(max_length=255)
    suggestion_text = models.TextField()
    guide = models.ForeignKey(Guide, models.DO_NOTHING)
    user = models.ForeignKey(User, models.DO_NOTHING)

    class Meta:
        managed = True
        db_table = 'guide_feedback'


class Hitchspot(models.Model):
    latitude = models.FloatField()
    longitude = models.FloatField()
    description = models.TextField(blank=True, null=True)
    avg_hitchability = models.FloatField()
    avg_waiting_time = models.FloatField()
    creation_date = models.DateField(auto_now_add=True)
    last_update = models.DateField(blank=True, null=True)
    country = models.ForeignKey(Country, models.DO_NOTHING)
    # user = models.ForeignKey(MyUser, models.DO_NOTHING)
    user = models.ForeignKey(User, models.DO_NOTHING)

    @property
    def photos(self):
        with connection.cursor() as cursor:
            cursor.execute('SELECT * '
                           'FROM photo '
                           'WHERE spot_id = %s', [self.id])
            photos = cursor.fetchall()
        return photos

    @property
    def comments(self):
        res_comments = Comment.objects.raw('SELECT * '
                                           'FROM comment '
                                           'WHERE parent_comment_id IS NULL AND spot_id = %s '
                                           'ORDER BY id ASC', [self.id])
        res_comments_list = []
        for comment in res_comments:

hitchify/forms.py
# from django.forms import ModelForm
# from hitchify.models import Comment

from django import forms
from django.forms import SelectDateWidget

from . import models

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['body_text', 'parent_comment']


class AddPostForm(forms.ModelForm):
    class Meta:
        model = models.ForumPost
        fields = ['title', 'body_text']


class AddGuideForm(forms.ModelForm):
    class Meta:
        model = models.Guide
        fields = ['title', 'body_text', 'short_summary']


class AddCountryForm(forms.ModelForm):
    class Meta:
        model = models.Country
        fields = ['country_name', 'short_description', 'national_currency']


class AddLanguageForm(forms.ModelForm):
    class Meta:
        model = models.Language
        fields = ['language_name']


class ConnectLangCountry(forms.ModelForm):
    class Meta:
        model = models.LanguageToCountry
        fields = ['country', 'language']


class CustomSignUpForm(UserCreationForm):

    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()

    birth_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    gender = forms.ChoiceField(choices=(('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')))
    res_country = forms.CharField()
    res_city = forms.CharField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password1', 'password2', 'email', 'birth_date', 'gender', 'res_country', 'res_city']
        # widgets = {
        #     'birth_date': forms.DateInput(attrs={'class':'datepicker'}),
        # }

hitchify/templates/countries.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="sub-container">
        <div class="sub-container-title">🌐 Countries</div>

        <ul>
            {% for c in countries %}
                <li>
                    <a href="{% url 'country' c.id %}">{{ c.country_name }}</a>
                </li>
            {% endfor %}
        </ul>

    </div>
{% endblock %}

hitchify/templates/country.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="sub-container">

        <table style="width:auto">
            <tr>
                <td style="border-color:rgb(47, 52, 55)">
                    <div class="sub-container-title">
                        <span class="countryname" id="country_title">{{ country.country_name }}</span>
                    </div>
                </td>
                <td style="border-color:rgb(47, 52, 55)" valign="top">
                    <div style="margin:16px 0 0 0px">
                        <a href="{% url 'map_country' country.id %}">
                            <button class="button-style">Show on Map</button>
                        </a>
                    </div>
                </td>
            </tr>
        </table>

        {% if perms.hitchify.change_country %}
            <div>
                <a href="#" class="changelink" onclick="edit(); return false;">Edit</a>
            </div>
        {% endif %}

        <br>
        <div>ℹ️ <span id="country_short_description">{{ country.short_description }}</span></div>
        <br>
        <div>🗣️ Languages:
            {% for lang in country.languages %}
                {{ lang }};
            {% endfor %}
        </div>
        <div>💶 Currency: <span id="country_national_currency">{{ country.national_currency }}</span></div>
        <div>⭐ Hitchrating:
            {% if country.hitchrating == None %}
                No rating yet! Contribute by adding your hitchspots.
            {% else %}
                {{ country.hitchrating }}
            {% endif %}
        </div>

        <br>
        🦸🏾 Experts: <br>
        {% for expert in country.expert_users %}
        {{ expert.0 }} <br>
        {% endfor %}

        <br><br>
        🦈 Most active users: <br>
        {% for mau in country.most_active_user %}
        {{ mau.0 }} <br>
        {% endfor %}

        <br><br>
        👑 Loyalists: <br>
        {% if country.loyal_users %}
            {% for loyalist in country.loyal_users %}
                {{ loyalist.0 }}<br>
            {% endfor %}
        {% endif %}

        <div class="tab">
            <button id="button_1" class="tablinks active" onclick="openTab(1,'country-hitchspots')">Hitchspots</button>
            <button id="button_2" class="tablinks" onclick="openTab(2, 'country-posts')">Posts</button>
        </div>

        <div id="country-hitchspots" class="tabcontent">
            <div class="top-toolbar" style="margin-top: 0">
{#                <form id="filter-hitchspot">#}
                    <input class="input_black" id="filter_query_hs" name="query" placeholder="Query">
                    <select class="select_black" id="filter_select_hs" name="select">
                        {# <option>Date</option> #}
                        <option value="1" selected>Hitchability</option>
                        <option value="2">Waiting time</option>
                        <option value="3">Added by</option>
                    </select>
                    <button onclick="filter_hs()" type="submit" class="button-style">Filter</button>
{#                </form>#}
            </div>
            <table class="table" id="table_hs">
                <thead>
                <tr>
                    <th>🧭 Coordinates</th>
                    <th>🔍 Description</th>
                    <th>👍 Hitchability</th>
                    <th>🕑 Waiting time</th>
                    <th>📆 Created</th>
                    <th>📆 Updated</th>
                    <th>👤 Added by</th>
                    <th></th>
                </tr>
                </thead>
                <tbody id="hitchspots-grid">
                {% for spot in country.hitchspots %}
                    <tr id="hs_{{ spot.id }}">
                        <td>{{ spot.latitude }};
                            {{ spot.longitude }}</td>
                        <td>{{ spot.description }}</td>
                        <td attr_ah="{{ spot.id }}">{{ spot.avg_hitchability }}</td>
                        <td attr_aw="{{ spot.id }}">{{ spot.avg_waiting_time }}</td>
                        <td>{{ spot.creation_date }}</td>
                        <td>{{ spot.last_update }}</td>
                        <td attr_ad="{{ spot.id }}">{{ spot.user }}</td>
                        <td>
                             <a href="{% url 'hitchspot' spot.id %}">
                                <button id="add-hitchspot" class="button-style">Open</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <div class="bottom-toolbar">
                <a href="{% url 'map_country' country.id %}">
                    <button id="add-hitchspot" class="button-style">Add</button>
                </a>
            </div>
        </div>

        <div id="country-posts" class="tabcontent">
            <div class="top-toolbar" style="margin-top: 0">
                {# <form id="filter-posts"> #}
                    <input class="input_black" id="filter_query" name="query" placeholder="Query">
                    <select class="select_black" id="filter_select" name="select">
                        <option value="1" selected>Title</option>
                        <option value="2">Author</option>
                    </select>
                    <button onclick="filter()" type="submit" class="button-style">Filter</button>
                {# </form> #}
            </div>

            <table id="table_post" class="table">
                <thead>
                <tr>
                    <th>🔖 Title</th>
                    <th>👤 Author</th>
                    <th>📆 Created</th>
                    <th>📆 Updated</th>
                    <th>❤ Likes</th>
                    <th></th>
                </tr>
                </thead>
                <tbody id="posts-grid">
                {% for post in country.forum_posts %}
                    <tr id="post_{{ post.id }}">
                        <td attr_title="{{ post.id }}">{{ post.title }}</td>
                        <td attr_user="{{ post.id }}">{{ post.username }}</td>
                        <td>{{ post.creation_date }}</td>
                        <td>
                            {% if post.last_update is not None %}
                                {{ post.last_update }}
                            {% else %}
                                -/-
                            {% endif %}
                        </td>
                        <td>
                            {% if post.likes is not None %}
                                {{ post.likes }}
                            {% else %}
                                0
                            {% endif %}
                        </td>
                        <td>
                            <form action="{% url 'post' post.id %}">
                                <button type="submit" class="button-style">Open</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <div class="bottom-toolbar">
                <form action="{% url 'add_post' country.id %}"
                      method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="button-style">Add</button>
                </form>
            </div>

        </div>
    </div>

    <div id="dialog" style="display: none">
    </div>

    <script>
        function filter() {
            let filter = $('#filter_select').val();
            let filter_query = $('#filter_query').val();

            if (filter == 1) {
                $('#table_post td[attr_title]').each(function (index, element) {
                    let str = $(element).html();

                    if (!str.match(filter_query)) {
                        $('#post_'+$(element).attr('attr_title')).hide();
                    } else {
                        $('#post_'+$(element).attr('attr_title')).show();
                    }
                });
            } else {
                $('#table_post td[attr_user]').each(function (index, element) {
                    let str = $(element).html();

                    if (!str.match(filter_query)) {
                        $('#post_'+$(element).attr('attr_user')).hide();
                    } else {
                        $('#post_'+$(element).attr('attr_user')).show();
                    }
                });
            }
        }

        function filter_hs() {
            let filter = $('#filter_select_hs').val();
            let filter_query = $('#filter_query_hs').val();

            if (filter == 1) {
                $('#table_hs td[attr_ah]').each(function (index, element) {
                    let str = $(element).html();

                    if (!str.match(filter_query)) {
                        $('#hs_' + $(element).attr('attr_ah')).hide();
                    } else {
                        $('#hs_' + $(element).attr('attr_ah')).show();
                    }
                });
            } else if (filter == 2) {
                $('#table_hs td[attr_aw]').each(function (index, element) {
                    let str = $(element).html();

                    if (!str.match(filter_query)) {
                        $('#hs_'+$(element).attr('attr_aw')).hide();
                    } else {
                        $('#hs_'+$(element).attr('attr_aw')).show();
                    }
                });
            } else {
                $('#table_hs td[attr_ad]').each(function (index, element) {
                    let str = $(element).html();

                    if (!str.match(filter_query)) {
                        $('#hs_'+$(element).attr('attr_ad')).hide();
                    } else {
                        $('#hs_'+$(element).attr('attr_ad')).show();
                    }
                });
            }
        }

        function openTab(evt, tabName) {
            let i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent");
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablinks");

            let ii = 0;
            if (evt == 1) {
                ii = 1;
            }

            for (i = ii; i < tablinks.length; i++) {

                tablinks[i].className = tablinks[i].className.replace(" active", "");
            }
            document.getElementById(tabName).style.display = "block";
            $('#button_'+evt).addClass('active');
        }

        let doc_url = document.location.href+'';

        if (doc_url.match(/posts$/) != null) {
            openTab(2, 'country-posts');
        } else {
            openTab(1, 'country-hitchspots');
        }

        let form_country = '<form action="/country/{{ country.id }}/edit" method="post">' +
            '{% csrf_token %}' +
            'Country name:<br>' +
            '<input required name="country_name" id="edit_title">' +
            '<br>Short description:<br>' +
            '<textarea required name="short_description" style="width:400px; height:100px" id="edit_short_description"></textarea>' +
            '<br>National currency:<br>' +
            '<input required id="edit_national_currency" name="national_currency">' +
            '<br><br>' +
            '<button type="submit" class="button-style">Edit</button>' +
            '</form>';

        function edit() {
            $('#dialog').prop('title', 'Edit country');
            $('#dialog').html(form_country);

            $('#edit_title').val($('#country_title').html());
            $('#edit_short_description').val($('#country_short_description').html());
            $('#edit_national_currency').val($('#country_national_currency').html());


            $("#dialog").dialog({
                width: 550,
                modal: true,
                position: { my: "center", at: "top+450", of: window }
            });
        }


    </script>

{% endblock %}


hitchify/templates/forum.html
{% extends "base_generic.html" %}

{% block content %}

<div class="sub-container">
    <div class="sub-container-title">💬 Forum</div>

    <div class="top-toolbar">
        <form id="filter">
            <input class="input_black" name="query" placeholder="Query">
            <select class="select_black" name="select">
                <option selected >Title</option>
                <option >Country</option>
                <option >Author</option>
            </select>
            <button type="submit" class="button-style">Filter</button>
        </form>
    </div>

    <table class="table">
        <thead>
        <tr>
            <th>🔖 Title</th>
            <th>🌐 Country</th>
            <th>👤 Author</th>
            <th>📆 Created</th>
            <th>📆 Updated</th>
            <th>❤ Likes</th>
            <th></th>
        </tr>
        </thead>
        <tbody id="posts-grid">
        {% for post in forum %}
        <tr>
            <td>{{post.title}}</td>
            <td>{{post.country_id}}</td>
            <td>{{post.user_id}}</td>
            <td>{{post.creation_date}}</td>
            <td>{{posts.last_update}}</td>
			<td>{{posts.likes}}</td>
            <td>
                <a href="{% url 'post' %}"><button class="grid-button">Open</button></a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="bottom-toolbar" >
        <button id="add-post" class="button-style">Add</button>
    </div>
</div>

{% endblock %}

hitchify/templates/map_xml.html
<?xml version='1.0' ?>
	<markers>
		<hs>
			{% for marker in hitchspots %}
				<marker lat="{{ marker.latitude }}" 
					lng="{{ marker.longitude }}" 
					av_h="{{ marker.avg_hitchability }}" 
					av_wt="{{ marker.avg_waiting_time }}" 
					desc="{{ marker.description }}"
                    id="{{ marker.id }}"
                />
			{% endfor %}
		</hs>
	</markers>